; UMCA - ESP32 NFC Reader (GERBANG SEKOLAH) - PlatformIO config
; Upload: pio run -t upload

[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM5
upload_speed = 115200
upload_flags =
    --before
    no_reset
build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    tzapu/WiFiManager@^2.0.17
    bblanchon/ArduinoJson@^7.4.3
    miguelbalboa/MFRC522@^1.4.11
    DFRobot/DFRobotDFPlayerMini@^1.0.4
